syntax on
filetype plugin on
filetype indent on

colorscheme nibble

" Options {{{
set autoindent
set autoread
set background=dark
set backspace=eol,indent,start
set belloff=all
set clipboard=unnamedplus
set colorcolumn=+1
set completeopt=menuone,noinsert,noselect
set encoding=utf-8
set expandtab
set fileencoding=utf-8
set foldmethod=indent
set guicursor=i-r-ci-cr:blinkwait300-blinkon200-blinkoff150,a:block
set hidden
set ignorecase
set incsearch
set iskeyword+=-
set laststatus=2
set lazyredraw
set linebreak
set list
set listchars=tab:▸\ ,nbsp:~,trail:.
set mouse=a
set nobackup
set nofoldenable
set nohlsearch
set noswapfile
set nowrap
set number relativenumber
set path=.,**
set runtimepath+=/usr/local/opt/fzf
set scrolloff=8
set shiftwidth=4
set showcmd
set sidescrolloff=8
set smartcase
set smartindent
set softtabstop=4
set splitright
set tabstop=4
set textwidth=80
set updatetime=1000
set wildignore+=**/node_modules/**/*,*.lock,**/target/**/*
set wildmode=longest:full,full
"}}}

" Remaps {{{
let mapleader = "\<space>"

" Edit and source $MYVIMRC
nnoremap <leader>ve :vsplit $MYVIMRC<cr>
nnoremap <leader>vs :source $MYVIMRC<cr>

" Disable arrow keys
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap <up> <nop>

" Window navigation
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
nnoremap <c-x> <c-w>x

" Visual mode utils
vnoremap < <gv
vnoremap > >gv
vnoremap p "_dP
" }}}

" Plugins {{{
" NERDTree specific bindings and settings
let g:NERDTreeCascadeSingleChildDir=0
let g:NERDTreeDirArrowCollapsible = "▿"
let g:NERDTreeDirArrowExpandable = "▹"
let g:NERDTreeHighlightCursorline=0
let g:NERDTreeMinimalUI=1
let g:NERDTreeShowHidden=1

nnoremap <expr> <silent> <c-b> g:NERDTree.IsOpen() ? ":NERDTreeClose<cr>" : @% == "" ? ":NERDTree<cr>" : ":NERDTreeFind<cr>"
"}}}
