syntax on
filetype plugin on
filetype indent on

colorscheme nord

let &t_SI.="\e[5 q"
let &t_SR.="\e[3 q"
let &t_EI.="\e[2 q"

" Options {{{
set autoindent
set autoread
set background=dark
set backspace=eol,indent,start
set belloff=all
set clipboard=unnamedplus
set colorcolumn=120
set completeopt=menuone,noinsert,noselect
set encoding=utf-8
set expandtab
set fileencoding=utf-8
set foldmethod=indent
set hidden
set ignorecase
set incsearch
set iskeyword+=-
set laststatus=2
set lazyredraw
set linebreak
set list
set listchars=tab:▸\ ,trail:.
set mouse=a
set nobackup
set nofoldenable
set noswapfile
set nowrap
set number relativenumber
set path=.,**
set runtimepath+=/usr/local/opt/fzf
set scrolloff=8
set sidescrolloff=8
set shiftwidth=4
set showcmd
set smartcase
set smartindent
set softtabstop=4
set splitright
set tabstop=4
set wildignore=**/node_modules/**/*
set wildmode=longest:full,full
"}}}

" Remaps {{{
let mapleader = "\<space>"

" Edit and source vimrc
nnoremap <leader>ve :vsplit $MYVIMRC<cr>
nnoremap <leader>vs :source $MYVIMRC<cr>

" Disable arrow keys
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap <up> <nop>

" Window navigation
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

" Visual mode utils
vnoremap < <gv
vnoremap > >gv
vnoremap p "_dP
" }}}

" Plugins {{{
" NERDTree specific bindings and settings
let g:NERDTreeShowHidden=1
let g:NERDTreeMinimalUI=1
let g:NERDTreeDirArrowExpandable = "▹"
let g:NERDTreeDirArrowCollapsible = "▿"

nnoremap <expr> <silent> <c-b> g:NERDTree.IsOpen() ? ":NERDTreeClose<CR>" : @% == "" ? ":NERDTree<CR>" : ":NERDTreeFind<CR>"
"}}}
