# start the notification daemon (dunst)
exec /usr/bin/dunst &

# start the compositor manager (picom)
exec /usr/bin/picom -b &

# start the network manager applet (nm-applet)
exec /usr/bin/nm-applet --sm-disable &

# start the window manager status bar (dwmblocks)
exec /usr/local/bin/slstatus &

# start the ssh-agent and the window manager (dwm)
exec /usr/bin/ssh-agent /usr/local/bin/dwm > $XDG_STATE_HOME/dwm.log
