#!/bin/zsh

# NOTE: Default configuration for my window manager.
#
# If using a desktop manager this file should be symlinked to the appropriate
# place as specified in the ".desktop" file and make it executable.
#
# ln -sv $XDIR/client/xinitrc /usr/local/bin/dwmstart
# chmod +x /usr/local/bin/dwmstart
#
# start the notification daemon (dunst)
exec /usr/bin/dunst &

# start the compositor manager (picom)
exec /usr/bin/picom -b &

# start the network manager applet (nm-applet)
exec /usr/bin/nm-applet --sm-disable &

# start the window manager status bar (dwmblocks)
exec /usr/local/bin/slstatus &

# start the ssh-agent and the window manager (dwm)
exec /usr/bin/ssh-agent /usr/local/bin/dwm

# vim: ft=sh
