# Start the notification daemon (dunst)
exec /usr/bin/dunst &

# start the compositor manager (picom)
exec /usr/bin/picom -b &

# start the network manager applet (nm-applet)
exec /usr/bin/nm-applet --sm-disable &

# Start the ssh-agent and the window manager (dwm)
exec /usr/bin/ssh-agent /usr/local/bin/dwm > $CACHEDIR/dwm.log
