# Taps
tap 'cmoscofian/meli'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

# Binaries
brew 'fzf'
brew 'gnupg'
brew 'go'
brew 'htop'
brew 'neovim'
brew 'nvm'
brew 'pinentry-mac'
brew 'protobuf'
brew 'python'
brew 'ripgrep'
brew 'sqlite'
brew 'tmux'
brew 'universal-ctags'

# Casks
cask 'brave-browser'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'insomnia'
cask 'intellij-idea'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'telegram'
cask 'whatsapp'

# Fonts
cask 'font-iosevka-nerd-font'

