[ -f "$UTILSDIR/common" ] && source "$UTILSDIR/common"
common::add_folder "$UTILSDIR"

autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''
zstyle ':completion::complete:*' cache-path "$XDG_CACHE_HOME/.zcompcache"

zmodload zsh/complist
compinit -d "$XDG_STATE_HOME/.zcompdump"
_comp_options+=(globdots) # Complete hidden files

autoload -U add-zsh-hook

common::add_folder "$SHELLDIR/functions"
common::add_file "$SHELLDIR/shell-aliases"
common::add_file "$SHELLDIR/shell-secrets"
common::add_file "$SHELLDIR/shell-work"
common::add_file "$ZSHDIR/zsh-utils"
zsh::add_file "zsh-options"
zsh::add_file "zsh-prompt"
zsh::add_file "zsh-vcs"
zsh::add_file "zsh-vim"
zsh::add_file "zsh-widgets"
common::add_file "/usr/share/fzf/completion.zsh"
common::add_file "/usr/share/fzf/key-bindings.zsh"
common::add_file "$SDKMAN_DIR/bin/sdkman-init.sh" # This loads sdkman
common::add_file "$NVM_DIR/nvm.sh" # This loads nvm
common::add_file "$NVM_DIR/bash_completion" # This loads nvm bash_completion
