export HISTFILE="$CACHEDIR/.zhistory"
export HISTSIZE=12000
export SAVEHIST=10000

[[ -f "$UTILSDIR/common" ]] && source "$UTILSDIR/common"
common::add_folder "$UTILSDIR"

autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''
zstyle ':completion::complete:*' cache-path "${CACHEDIR}/.zcompcache"

zmodload zsh/complist
compinit -d "$CACHEDIR/.zcompdump"
_comp_options+=(globdots) # Complete hidden files

autoload -U add-zsh-hook

common::add_folder "$SHELLDIR/functions"
common::add_file "$SHELLDIR/shell-aliases"
common::add_file "$SHELLDIR/shell-secrets"
zsh::add_file "zsh-options"
zsh::add_file "zsh-vcs"
zsh::add_file "zsh-vim"
zsh::add_file "zsh-prompt"
common::add_file "/usr/local/opt/fzf/shell/completion.zsh"
common::add_file "/usr/local/opt/fzf/shell/key-bindings.zsh"
common::add_file "$SDKMAN_DIR/bin/sdkman-init.sh" # This loads sdkman
common::add_file "/usr/local/opt/nvm/nvm.sh" # This loads nvm
common::add_file "/usr/local/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion

# Set all work cloned projects as environment variables
f::workset $WORK_PROJECTS
