export HISTFILE="$CACHEDIR/.zhistory"
export HISTSIZE=12000
export SAVEHIST=10000

[[ -f "$ZDOTDIR/zsh-functions" ]] && source "$ZDOTDIR/zsh-functions"
[[ -f "$SHELLDIR/shell-functions" ]] && source "$SHELLDIR/shell-functions"

autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''

zmodload zsh/complist
compinit -d "$CACHEDIR/.zcompdump"
_comp_options+=(globdots) # Complete hidden files

autoload -U add-zsh-hook

add_file "$SHELLDIR/shell-aliases"
add_file "$SHELLDIR/shell-secrets"
add_folder "$SHELLDIR/functions"
zsh_add_file "zsh-options"
zsh_add_file "zsh-vcs"
zsh_add_file "zsh-vim"
zsh_add_file "zsh-prompt"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "$HOME/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Set all meli cloned projects as environment variables
f_workset $MELI_PROJECTS

